# Chapter 6: 특이값 분해

## 행렬 C의 특이값 분해를 살펴보자

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm


# 행렬 C를 선언해보자.
# 책의 예제와 같은 행렬을 사용한다.
C = np.array([
    [9, 2],
    [24, 8],
    [39, 14]
])

# numpy의 svd 메소드를 이용해, 특이값 분해를 수행한다.
U, sigma, Vt = np.linalg.svd(C)

print(f"U = \n {U}")
print(f"sigma = \n {sigma}")

# Sigma에 대해 살펴보자.
# Sigma는 C와 그 모양이 같다. 따라서 다음과 같이 C 와 같은 모양의 0행렬을 만들어준다.
Sigma = np.zeros(C.shape)
m = np.amin(C.shape)
Sigma[0:m, 0:m] = np.diag(sigma)
print(f"Sigma = \n {Sigma}")
print(f"Vt = \n {Vt}")

U = 
 [[-0.18537573  0.89385076  0.40824829]
 [-0.51204594  0.26672511 -0.81649658]
 [-0.83871616 -0.36040053  0.40824829]]
sigma = 
 [49.4022666  1.1899809]
Sigma = 
 [[49.4022666  0.       ]
 [ 0.         1.1899809]
 [ 0.         0.       ]]
Vt = 
 [[-0.94464116 -0.32810529]
 [ 0.32810529 -0.94464116]]
